apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.name }}
spec:
  gatewayClassName: {{ .Values.name }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
