replicaCount: 1
ns: app

image:
  repository: stack-app-template-dev
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to .Chart.AppVersion

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

postgresql:
  host: ""  # Default is constructed using clusterName below
  port: 5432
  database: app

  # CloudNativePG-specific settings
  clusterName: postgres
  credentialsSecret: postgres-credentials

env: []
