# yaml-language-server: $schema=./schema.json

namespace: app

cluster:
  name: postgres
  instances: 1
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "500Mi"
  storage:
    size: "1Gi"
    storageClass: "standard"
  imageName: "ghcr.io/cloudnative-pg/postgresql:17"
  backup:
    enabled: false

  monitoring:
    enabled: false

bootstrap:
  initdb:
    database: app
    owner: app
    secret:
      name: postgres-credentials

postgresql:
  parameters:
    max_connections: "100"
    shared_buffers: "256MB"






